packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  mongodb-memory-server: true
  prisma: true
  sharp: true
  unrs-resolver: true
